name: LoL-Tracker3-dev
services:
  web:
    container_name: web
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        VITE_SENTRY_ORG: ${VITE_SENTRY_ORG}
        VITE_SENTRY_PROJECT: ${VITE_SENTRY_PROJECT}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RIOT_API_KEY: ${RIOT_API_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      PORT: 3000
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - db
      - minio
    networks:
      - internal-net

  db:
    image: postgres:16-alpine
    container_name: db-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/share:/pgshare
      - ./db/scripts:/pgscripts:ro
    networks:
      - internal-net

  minio:
    image: minio/minio:latest
    container_name: lol-minio-dev
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9005:9005"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9005"
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
